services:
  - type: web
    name: grocery-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn ap:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PORT
        value: 10000
